apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  identity-volume
  labels:
    app: identity
    part: identity-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-db
  labels:
    app: identity
    part: identity-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
      part: identity-db
  template:
    metadata:
      labels:
        app: identity
        part: identity-db
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: identity-volume
      containers:
      - name: identity-db
        image: localhost:32000/postgres:13
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: identity-db-pwd
                key: pwd
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: storage
---
apiVersion: v1
kind: Service
metadata:
  name: identity-db
  labels:
    app: identity
    part: identity-db
spec:
  selector:
    part: identity-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432