on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.mk8s.lanodispenser.no
      APP: identity-client
    steps:
    - uses: actions/checkout@master
    
    - working-directory: client
      run: |
        docker build . -t $REGISTRY/$APP:${{ github.sha }}
        docker push $REGISTRY/$APP:${{ github.sha }}
      
      
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          client/deployment.yaml
        images: |
          $REGISTRY/$APP:${{ github.sha }}